uploads = []
generated = []

[[outputs]]
id = "XI5-7LVueZYbtNpMoNxqZ"
uri = "file://wager-race.zip"
type = "unspecified"
title = "wager-race — proyecto standalone"
logical_id = "83e811e9-52c9-4bef-bf2c-a3153e0c88b3"
